<#
    .SYNOPSIS
    Shared helper loader module for Baseline.

    .DESCRIPTION
    Dot-sources the helper slices from Module/SharedHelpers and exports the
    shared helper functions consumed across the project.
#>

# These script-scope variables are set before dot-sourcing any helper files.
# All helper files may reference them (they share this module's scope).
$Script:SharedHelpersModuleRoot = $PSScriptRoot
$Script:SharedHelpersRepoRoot = Split-Path $PSScriptRoot -Parent

# Load order matters: Manifest.Helpers depends on GameMode.Helpers (for
# Test-TweakManifestIntegrity), so GameMode.Helpers must be loaded first.
$HelperFiles = @(
    'Localization.Helpers.ps1'
    'ErrorHandling.Helpers.ps1'
    'Registry.Helpers.ps1'
    'Environment.Helpers.ps1'
    'GameMode.Helpers.ps1'
    'Manifest.Helpers.ps1'
    'ScenarioMode.Helpers.ps1'
    'Preset.Helpers.ps1'
    'Recovery.Helpers.ps1'
    'PackageManagement.Helpers.ps1'
    'AdvancedStartup.Helpers.ps1'
    'Taskbar.Helpers.ps1'
    'SystemMaintenance.Helpers.ps1'
    'Persistence.Helpers.ps1'
    'ConfigProfile.Helpers.ps1'
    'StateCapture.Helpers.ps1'
    'Compliance.Helpers.ps1'
    'AuditTrail.Helpers.ps1'
    'Scheduler.Helpers.ps1'
    'RemoteTarget.Helpers.ps1'
)

# Dot-sourcing runs each helper file in this module's scope (not an isolated
# child scope). This is intentional: helpers share $Script:-scoped state
# (e.g., $Script:SharedHelpersModuleRoot) and all exported functions land in
# one flat module namespace. The trade-off is that helpers can accidentally
# shadow each other's private variables - use distinctive names to avoid this.
foreach ($helperFile in $HelperFiles)
{
    $helperPath = Join-Path -Path (Join-Path $PSScriptRoot 'SharedHelpers') -ChildPath $helperFile
    if (-not (Test-Path -LiteralPath $helperPath))
    {
        throw "Required shared helper file is missing: $helperPath"
    }

    . $helperPath
}

$ExportedFunctions = @(
    'Resolve-BaselineLocalizationDirectory'
    'Import-BaselineLocalization'
    'Remove-HandledErrorRecord'
    'Test-IgnorableErrorMessage'
    'Test-IgnorableErrorRecord'
    'Get-NewUnhandledErrorRecords'
    'Get-BaselineErrorCatalog'
    'Resolve-BaselineErrorCode'
    'Get-BaselineErrorInfo'
    'Format-BaselineErrorDialogMessage'
    'Invoke-SilencedProgress'
    'Set-Policy'
    'ConvertTo-NativeRegistryPath'
    'ConvertTo-RegExeValueType'
    'Dismount-RegistryHive'
    'Mount-RegistryHive'
    'Test-RegistryValueEquivalent'
    'Set-RegistryValueSafe'
    'Remove-RegistryValueSafe'
    'Set-SystemTweaksRegistryValue'
    'Remove-SystemTweaksRegistryValue'
    'Initialize-ForegroundWindowInterop'
    'Initialize-ConsoleWindowInterop'
    'Get-ConsoleHandle'
    'Hide-ConsoleWindow'
    'Show-ConsoleWindow'
    'Test-InteractiveHost'
    'Initialize-WpfWindowForeground'
    'Get-WindowsVersionData'
    'Get-OSInfo'
    'Get-LocalizedShellString'
    'ConvertTo-WindowsDisplayVersionComparable'
    'Test-Windows11FeatureBranchSupport'
    'Show-BootstrapLoadingSplash'
    'Close-LoadingSplashWindow'
    'Show-Menu'
    'Restart-Script'
    'Get-BaselineDisplayVersion'
    'Get-TweakSkipLabel'
    'Stop-Foreground'
    'Invoke-UCPDBypassed'
    'Get-UCPDTemporaryPowerShellPath'
    'Convert-JsonManifestValue'
    'ConvertTo-TweakRiskLevel'
    'ConvertTo-TweakPresetTier'
    'ConvertTo-TweakWorkflowSensitivity'
    'Convert-ToWhyThisMattersText'
    'Import-TweakManifestFromData'
    'Get-ValidScenarioTagCatalog'
    'Get-ValidGamingPreviewGroups'
    'Get-ValidGameModeProfileNames'
    'Test-TweakManifestIntegrity'
    'Get-ManifestEntryByFunction'
    'Get-TweakManifestDefaultCommand'
    'Get-ScenarioProfileDefinitions'
    'Get-ScenarioProfileValidationIssues'
    'Get-ScenarioProfilePlan'
    'Get-ScenarioProfileCommandList'
    'ConvertTo-HeadlessPresetName'
    'Get-HeadlessPresetCommandList'
    'Get-GameModeAllowlist'
    'Get-GameModeReviewedCrossCategoryAllowlist'
    'Import-GameModeAllowlistData'
    'Import-GameModeAdvancedData'
    'Import-GameModeProfileData'
    'Get-GameModeAdvancedFunctions'
    'Resolve-GameModeAllowlistToggleParam'
    'Get-GameModeProfileDefinitions'
    'Get-GameModeDecisionPromptKeyCatalog'
    'Get-GameModeDecisionPromptDefinitions'
    'Get-GameModeDecisionOverridesText'
    'Resolve-ValidatedGameModeDecisionOverrides'
    'Test-GameModeAllowlistEntryReviewed'
    'Test-GameModeProfileDefaultEligible'
    'Merge-GameModeSelectionState'
    'Get-GameModeSelectionSet'
    'Get-GameModeProfilePlan'
    'Get-GameModeProfileCommandList'
    'Get-DirectUndoCommandForEntry'
    'Test-ShouldRecommendRestorePoint'
    'Update-ProcessPathFromRegistry'
    'Resolve-WinGetExecutable'
    'Get-WinGetVersion'
    'Invoke-DownloadFile'
    'Set-DownloadSecurityProtocol'
    'Assert-FileHash'
    'Assert-AuthenticodeSignature'
    'Get-PowerShellInstallerArchitecture'
    'Resolve-PowerShellInstallerUri'
    'Get-OneDriveSetupPath'
    'ConvertTo-NormalizedVersion'
    'Get-InstalledVCRedistVersion'
    'Get-InstalledDotNetRuntimeVersion'
    'Get-LatestDotNetRuntimeRelease'
    'Install-VCRedist'
    'Install-DotNetRuntimes'
    'Get-AdvancedStartupDesktopDirectory'
    'Get-AdvancedStartupDownloadsDirectory'
    'Get-AdvancedStartupAssetPath'
    'Get-AdvancedStartupIconLocation'
    'Enable-AdvancedStartupWindowsRecoveryEnvironment'
    'Get-AdvancedStartupCommandPath'
    'Set-AdvancedStartupCommandFile'
    'Get-AdvancedStartupShortcutArguments'
    'Get-TaskbarPinnedItems'
    'Get-TaskbarPinnedMatches'
    'Get-TaskbarUnpinVerbCandidates'
    'Set-NewsInterestsTaskbarViewMode'
    'Invoke-TaskbarUnpin'
    'Remove-TaskbarPinnedLink'
    'Invoke-TaskbarUnpinWithFallback'
    'Remove-TaskbarPinnedLinksByPattern'
    'Invoke-ARM64ShellUnpin'
    'Test-Windows11SmbDuplicateSidIssue'
    'Invoke-AdditionalServiceOptimizations'
    'Get-BaselineDataDirectory'
    'Write-BaselineDocument'
    'Read-BaselineDocument'
    'Add-BaselineAuditRecord'
    'Read-BaselineAuditLog'
    'Test-BaselineDocumentSchema'
    'New-ConfigurationProfile'
    'Export-ConfigurationProfile'
    'Import-ConfigurationProfile'
    'Test-ConfigurationProfileCompatibility'
    'Compare-ConfigurationProfiles'
    'ConvertFrom-PresetToProfile'
    'Get-TweakCurrentStateValue'
    'New-SystemStateSnapshot'
    'Compare-SystemStateSnapshots'
    'Export-SystemStateSnapshot'
    'Import-SystemStateSnapshot'
    'Get-TweakPlannedStateValue'
    'Limit-SnapshotDirectory'
    'Test-SystemCompliance'
    'Get-DriftedEntries'
    'Get-ComplianceFixList'
    'Export-ComplianceReport'
    'Get-AuditLogPath'
    'Write-AuditRecord'
    'Get-AuditLog'
    'Export-AuditReport'
    'Clear-AuditLog'
    'Register-BaselineScheduledTask'
    'Unregister-BaselineScheduledTask'
    'Get-BaselineScheduledTasks'
    'Test-BaselineScheduledTaskExists'
    'Test-BaselineRemoteConnectivity'
    'Invoke-BaselineRemoteCompliance'
    'Invoke-BaselineRemoteApply'
)

Export-ModuleMember -Function $ExportedFunctions
